### ISSUE TITLE
Error when compiling from command prompt

### ISSUE THREAD

**Issue by terabyte25** [moien007/dumpsc#2]
C:\WINDOWS\Microsoft.NET\Framework\v3.5\csc.exe dumpsc.sln
Microsoft (R) Visual C# 2008 Compiler version 3.5.30729.8763
for Microsoft (R) .NET Framework version 3.5
Copyright (C) Microsoft Corporation. All rights reserved.

dumpsc.sln(3,3): error CS1024: Preprocessor directive expected
dumpsc.sln(3,10): error CS1025: Single-line comment or end-of-line expected
dumpsc.sln(6,71): error CS1009: Unrecognized escape sequence
dumpsc.sln(2,1): error CS0116: A namespace does not directly contain members such as fields or methods

**Comment by moien007** [comment]
You Need Visual C# 2015

**Comment by Demonisius666** [comment]
http://prntscr.com/k6p6o6
Exception when try do decompress sc files clash of clans

**Comment by moien007** [comment]
Sorry for late answer, I didn't check this repo for a long time. [Read this](https://github.com/moien007/dumpsc/issues/5#issuecomment-463669618).
